### ISSUE TITLE
13 Clowns makes some movies not playable

### ISSUE THREAD

**Issue by peno64** [the13clowns/the13clowns.github.io#1]
It took me a long time to figure this out how it comes but now I found it.

I run kodi 18.1 on raspberry pi
I do a new install of this without any addon and I can play a certain movie without any problem.
When I install the 13Clowns addon, suddenly this movie doesn't play anymore. The sound is there but no or messed up video. Other video's play without a problem. I don't have the issue with other addons installed like yoda. This is just an example video giving the problem there are others also.
The video has the following structure:
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.25 GiB
Duration                                 : 1 h 36 min
Overall bit rate                         : 1 857 kb/s
Movie name                               : Happy Death Day 2017  (1080p x265 10bit FS93 Joy)[UTR]
Encoded date                             : UTC 2018-10-23 21:58:27
Writing application                      : mkvmerge v28.1.0 ('Morning Child') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9
Cover                                    : Yes
Attachments                              : cover.jpg
Writing frontend                         : StaxRip v1.8.2.0

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 36 min
Bit rate                                 : 1 499 kb/s
Width                                    : 1 920 pixels
Height                                   : 800 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.041
Stream size                              : 1.01 GiB (81%)

When I disable the addon "13Clowns Video" and reboot the device it plays again.
However if I then go to "My Addons", "Video Addons" and position on the "13Clowns Video" item then I have the problem again until I reboot the device. But only if I have viewed the "13Clowns Video" item. I can move on all other items then I have no problem playing the video.

Then I noticed that there is one difference in 13Clowns compared to the other addons. It uses an animated gif to show its picture. And also on the main screen this same animated gif is shown.
So I changed this gif file by a non-animated gif and the problem was fixed.
Also if I Enable 13Clowns again such that it is shown on the kodi main screen (but now no animation anymore) then my movie is still ok.

So there seems to be either a problem in this animated gif or kodi doesn't really like this.

I hope you can do something with this and solve the problem (or don't use an animated gif anymore)

Thank you

**Comment by the13clowns** [comment]
Good find. The Exodus 13c is t animated. Maybe a better option. I like the animation. Sry
